#ifndef STRING
#endif

//General
STRING(LANGUAGE, "English");
STRING(UNNAMED, "Unnamed");
STRING(DESCRIPTION, "Paint with your paws on Game Boy Advance");

//Themes
STRING(THEME_WHITE, "White");
STRING(THEME_PINK_FOX, "Pink Fox");
STRING(THEME_MAID, "Maid");
STRING(THEME_ACE, "Ace");

//Icons
STRING(ICON_PRIDE, "Pride");
STRING(ICON_MONOCHROME, "Monochrome");

//Tools
STRING(TOOL, "Tool");
STRING(BRUSH, "Brush");
STRING(BRUSH_TYPE, "Type");
STRING(BRUSH_SIZE, "Size");
STRING(BRUSH_DIAMETER, "Diameter");
STRING(BRUSH_RADIUS, "Radius");
STRING(BRUSH_NOISE_SIZE, "Noise Size");
STRING(BRUSH_NOISE_SHIFT, "Noise Shift");
STRING(BRUSH_NOISE_OFFSET, "Noise Offset");
STRING(BRUSH_TYPE_SQUARE, "Square");
STRING(BRUSH_TYPE_CIRLCE, "Cirle");
STRING(BRUSH_TYPE_DOT, "Dot");
STRING(BRUSH_TYPE_SQUARE_NOISE, "Square Noise");
STRING(BRUSH_TYPE_CIRLCE_NOISE, "Cirle Noise");
STRING(BRUSH_TYPE_DOT_NOISE, "Dot Noise");
STRING(ERASER, "Eraser");
STRING(EYEDROPPER, "Eyedropper");
STRING(COLOR_PICKER, "Color Picker");
STRING(COLOR_PICKER_COLOR, "Color");
STRING(SAVING, "Saving");
STRING(SAVING_NEW, "New");
STRING(SAVING_LOAD, "Load");
STRING(SAVING_SAVE, "Save");
STRING(SAVING_SAVE_AS, "Save As");
STRING(SAVING_EXPORT, "Export");
STRING(SAVING_EXPORT_AS, "Export As");
STRING(SETTINGS, "Settings");
STRING(SETTINGS_THEME, "Theme");
STRING(SETTINGS_ICON, "Icon");
STRING(SETTINGS_LANGUAGE, "Language");
STRING(SETTINGS_DEFAULT, "Default");
STRING(INFO, "Info");
STRING(INFO_ABOUT, "About App");
STRING(INFO_BY, "By");